---
title: "R Notebook"
output: html_notebook
---

1 MVP
Using the dataset austen_books() from the package janeaustenr:

```{r}
library(tidyverse)
library(janeaustenr)
library(tidytext)
```

```{r}
pride_book <- tibble(
  id = 1:length(prideprejudice),
  text = prideprejudice
) %>% unnest_tokens(word, text, token = 'words')

ss_book <- tibble(
  id = 1:length(sensesensibility),
  text = sensesensibility
) %>% unnest_tokens(word, text, token = 'words')
```
Find the most common words in both Pride & Prejudice and Sense & Sensibility.
```{r}
pride_book %>% count(word, sort = TRUE)
ss_book %>% count(word, sort = TRUE)

#Pride and prejudice: the 
#sense and sensibility : to 
```
Find the most common words in both Pride & Prejudice and Sense & Sensibility, not including stop words.

```{r}
pride_book %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE)

ss_book %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE)

#Pride and prejudice: elizabeth
#sense and sensibility : elinor 
```
Find the most common sentiment words in both Pride & Prejudice and Sense & Sensibility.
```{r}
pride_book %>%
  anti_join(stop_words) %>% 
  inner_join(get_sentiments("bing"))

ss_book %>%
  anti_join(stop_words) %>% 
  inner_join(get_sentiments("bing"))
#Pride and prejudice: pride
#sense and sensibility : respectable 
```







